### ISSUE TITLE
Editor dont work

### ISSUE THREAD

**Issue by ghost** [DeltaNedas/modding-toolbox#1]
When i try to open map in editor an NullPointerException appears
When i create map game crash

Mindustry crash log:
Mindustry has crashed. How unfortunate.
Version: release build 121.4
OS: Windows 10 x32
Java Version: 1.8.0_261
Java Architecture: 32
2 Mods: modding-toolbox:3.7.1, ui-lib:2.16.6

```
java.lang.NullPointerException
	at mindustry.ctype.UnlockableContent.icon(UnlockableContent.java:85)
	at mindustry.editor.MapEditorDialog.rebuildBlockSelection(MapEditorDialog.java:711)
	at mindustry.editor.MapEditorDialog.addBlockSelection(MapEditorDialog.java:690)
	at arc.scene.ui.layout.Table.table(Table.java:244)
	at mindustry.editor.MapEditorDialog.lambda$build$62(MapEditorDialog.java:586)
	at arc.scene.ui.layout.Table.table(Table.java:244)
	at mindustry.editor.MapEditorDialog.build(MapEditorDialog.java:397)
	at arc.scene.ui.Dialog$5.shown(Dialog.java:377)
	at arc.scene.event.VisibilityListener.handle(VisibilityListener.java:11)
	at arc.scene.Element.notify(Element.java:162)
	at arc.scene.Element.fire(Element.java:133)
	at arc.scene.ui.Dialog.show(Dialog.java:417)
	at mindustry.editor.MapEditorDialog.show(MapEditorDialog.java:351)
	at mindustry.ui.dialogs.MapsDialog.lambda$setup$1(MapsDialog.java:51)
	at mindustry.core.UI.lambda$loadAnd$10(UI.java:246)
	at arc.util.Timer$1.run(Timer.java:88)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:148)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:43)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
```

**Comment by deltanedas** [comment]
map editor is from vanilla
