### ISSUE TITLE
bug with UI editor

### ISSUE THREAD

**Issue by EntropyAuthor** [DeltaNedas/modding-toolbox#2]
Platform: Android/iOS/Mac/Windows/Linux
Windows

Version: The version number in the mod tile title in the mod menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT VERSION NUMBER OF YOUR MOD.
1.0.0

Issue: Explain your issue in detail.
Creating then removing 2 UI elements crashes the game.
Steps to reproduce: How you happened across the issue, and what exactly you did to make the bug happen.
Create Row
Create Label
Delete Both
crash

Link(s) to mod(s) used: The mod repositories or zip files that are related to the issue, if applicable.
In crash report
(Crash) logs: Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.

Mindustry has crashed. How unfortunate.
Version: release build 122.1
OS: Windows 10 x64
Java Version: 1.8.0_72
Java Architecture: 64
52 Mods: [#624200]copper:2.4, cliff:1.1.0, hackustry:3.3.zip, invincible-cheat-mod-v6:2.7.0, modding-toolbox:3.7.1, pictologic:1.5.7, rtfm:2.12.2, time-control:0.2, ui-lib:2.16.4, unit-factory:2.3.0, [#25f12f]vanilla-extended[]:1.5, advancecontent:1.9.2 Final Major Update, aperture-science:0.2 dev, canvas:2.0, commandblocks:1.0, community-mod:1.2, entity-lib:1.3.0, example-mod:3.2, gamersmod:0.7667, inverted-machines:1.3, multi-lib2:1.1.4, ohno-missiles:4.3, sandy-sand:1.59, signals:1.0.0, skillplus:0.4, testing:1, tfsyes:420.69, the-playground:0.20.0, trains:0.01, vbucks:1.10.3, anuke-logic:1.6.1, badguns:0.1.1 alpha, classic-music:2.0, dev-mode:2.3.1, exotic-mod:2.4-beta-build247, hacker-tools:3.0.0, hackforall:0.1, larger-cores:1.0, mindustry-classic:0.1 alpha, multi-lib:1.0.7, pixelcraft:0.7, portal:0.1.0, purple-air:0.2.0, revision:6.2, routorio:2.35.2, speed:2.2.1, substructure:0.1, test-utils:0.3, testers:0.25, upgraded-factories:1.0, vanilla-enhanced:2, vanilla-upgraded:[white]3.0

rhino.EcmaError: TypeError: Cannot call method "remove" of null (uieditor#137)
	at rhino.ScriptRuntime.constructError(ScriptRuntime.java:3955)
	at rhino.ScriptRuntime.constructError(ScriptRuntime.java:3935)
	at rhino.ScriptRuntime.typeError(ScriptRuntime.java:3964)
	at rhino.ScriptRuntime.typeError2(ScriptRuntime.java:3980)
	at rhino.ScriptRuntime.undefCallError(ScriptRuntime.java:3994)
	at rhino.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2339)
	at rhino.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2333)
	at rhino.optimizer.OptRuntime.callProp0(OptRuntime.java:69)
	at rhino.gen.uieditor_48._c_anonymous_13(uieditor:137)
	at rhino.gen.uieditor_48.call(uieditor)
	at rhino.ContextFactory.doTopCall(ContextFactory.java:346)
	at rhino.ScriptRuntime.doTopCall(ScriptRuntime.java:3303)
	at rhino.gen.uieditor_48.call(uieditor)
	at rhino.ArrowFunction.call(ArrowFunction.java:33)
	at rhino.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:141)
	at rhino.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:92)
	at rhino.Context.call(Context.java:524)
	at rhino.ContextFactory.call(ContextFactory.java:446)
	at rhino.InterfaceAdapter.invoke(InterfaceAdapter.java:92)
	at rhino.jdk18.VMBridge_jdk18.lambda$newInterfaceProxy$0(VMBridge_jdk18.java:100)
	at com.sun.proxy.$Proxy4.run(Unknown Source)
	at arc.scene.Element.lambda$clicked$2(Element.java:893)
	at arc.scene.Element$4.clicked(Element.java:902)
	at arc.scene.event.ClickListener.touchUp(ClickListener.java:77)
	at arc.scene.event.InputListener.handle(InputListener.java:34)
	at arc.scene.Scene.touchUp(Scene.java:357)
	at arc.input.InputMultiplexer.touchUp(InputMultiplexer.java:137)
	at arc.input.InputEventQueue.drain(InputEventQueue.java:71)
	at arc.backend.sdl.SdlInput.update(SdlInput.java:102)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:143)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:43)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)

---

Place an X (no spaces) between the brackets to confirm that you have read the line below.

- [x] I have updated to the latest release to make sure my issue has not been fixed.
- [x] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by deltanedas** [comment]
ok

**Comment by deltanedas** [comment]
fixed
